name: Deploy to Azure Web App

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build Vite App
        run: |
          npm run build | tee build.log
          if [ ! -d "dist" ]; then
            echo "❌ Dist folder not found! Build failed."
            exit 1
          fi

      - name: Debug - List Dist Directory
        run: ls -al dist/

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/

      - name: Upload Build Logs
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: build.log

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: ./dist

      - name: Download Build Logs
        uses: actions/download-artifact@v4
        with:
          name: build-logs

      - name: Show Build Logs
        run: cat build.log || echo "Build log not found!"

      - name: Install PM2
        run: npm install pm2@latest -g

      - name: Start app with PM2
        run: pm2 serve ./dist --name "react-app" --spa

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'DevNGDTWebApp'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: './dist'


